### PR TITLE
Upgrade php-parser and allow 5.8 support

### PR DESCRIPTION
**Pull request by NoelDavies**
I've added support for laravel 5.8 (Breaking non-bc change due to DotEnv package)

There are no tests - so I can't add any tests for this, but yeah let me know what you think and thanks for the original package! 👍

### CODE REVIEW

**Comment by NoelDavies** [comment]
Not sure how to cure those merge conflicts because I'm overwriting that line completely :/

**Comment by NoelDavies** [comment]
Is this repo being maintained anymore?

**Comment by craigsansam** [comment]
@NoelDavies Sorry we missed this!

**Review by craigsansam — APPROVED** [review]

**Comment by NoelDavies** [comment]
@craigsansam is this going to get a version tag? requiring "dev-master" scares me xD

**Comment by craigsansam** [comment]
Doesn't look like we've tagged this before - so I've just tagged this as 1.1.0

**Pull request merged**
